int add(int x, int y);
int subtract(int x, int y);
int multiply(int x, int y);
int divide(int x, int y);


struct Student{
	int id;
};

int studentAdd(Student s, Student t);
Student getStudent(int id);


struct Vertex {
	int x;
	int y;
};


struct Rectangle{
	Vertex corner1;
	Vertex corner2;
};

int vertexAddXPos(Vertex x, Vertex y);
int vertexAddYPos(Vertex x, Vertex y);
Vertex createVertex(int x, int y);
Rectangle createRectangle(Vertex x, Vertex y);
int rectangleAdd(Rectangle r1, Rectangle r2);
float  rectangleCornerDistance(Rectangle r1);





